//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.AggregateReport.Api.V2.Dao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AggregateReportDaoV2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AggregateReportDaoV2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.AggregateReport.Api.V2.Dao.AggregateReportDaoV2", typeof(AggregateReportDaoV2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND spf_pass_dkim_pass_none &gt; 0.
        /// </summary>
        internal static string FilterByFullyTrusted {
            get {
                return ResourceManager.GetString("FilterByFullyTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AND (@ip IS NULL OR ip = @ip).
        /// </summary>
        internal static string FilterByIp {
            get {
                return ResourceManager.GetString("FilterByIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND (spf_fail_dkim_pass_none &gt; 0 OR spf_pass_dkim_fail_none &gt; 0).
        /// </summary>
        internal static string FilterByPartiallyTrusted {
            get {
                return ResourceManager.GetString("FilterByPartiallyTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND provider like @providerFilter.
        /// </summary>
        internal static string FilterByProvider {
            get {
                return ResourceManager.GetString("FilterByProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND (spf_pass_dkim_pass_quarantine &gt; 0 OR spf_pass_dkim_fail_quarantine &gt; 0 OR spf_fail_dkim_pass_quarantine &gt; 0 OR spf_fail_dkim_fail_quarantine &gt; 0).
        /// </summary>
        internal static string FilterByQuarantined {
            get {
                return ResourceManager.GetString("FilterByQuarantined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND (spf_pass_dkim_pass_reject &gt; 0 OR spf_pass_dkim_fail_reject &gt; 0 OR spf_fail_dkim_pass_reject &gt; 0 OR spf_fail_dkim_fail_reject &gt; 0).
        /// </summary>
        internal static string FilterByRejected {
            get {
                return ResourceManager.GetString("FilterByRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  AND spf_fail_dkim_fail_none &gt; 0.
        /// </summary>
        internal static string FilterByUntrused {
            get {
                return ResourceManager.GetString("FilterByUntrused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///effective_date,
        ///domain,
        ///provider,
        ///original_provider,
        ///reporter_org_name,
        ///ip,
        ///count,
        ///disposition,
        ///dkim,
        ///spf,
        ///envelope_to,
        ///envelope_from,
        ///header_from,
        ///organisation_domain_from,
        ///spf_auth_results,
        ///spf_pass_count,
        ///spf_fail_count,
        ///dkim_auth_results,
        ///dkim_pass_count,
        ///dkim_fail_count,
        ///forwarded,
        ///sampled_out,
        ///trusted_forwarder,
        ///mailing_list,
        ///local_policy,
        ///arc,
        ///other_override_reason,
        ///host_name,
        ///host_org_domain,
        ///host_provider,
        ///host_as_number,
        ///host_as_description,
        ///host_country,
        ///p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectAggregateExportData {
            get {
                return ResourceManager.GetString("SelectAggregateExportData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///effective_date,
        ///domain,
        ///provider,
        ///original_provider,
        ///reporter_org_name,
        ///ip,
        ///count,
        ///disposition,
        ///dkim,
        ///spf,
        ///envelope_to,
        ///envelope_from,
        ///header_from,
        ///organisation_domain_from,
        ///spf_auth_results,
        ///spf_pass_count,
        ///spf_fail_count,
        ///dkim_auth_results,
        ///dkim_pass_count,
        ///dkim_fail_count,
        ///forwarded,
        ///sampled_out,
        ///trusted_forwarder,
        ///mailing_list,
        ///local_policy,
        ///arc,
        ///other_override_reason,
        ///host_name,
        ///host_org_domain,
        ///host_provider,
        ///host_as_number,
        ///host_as_description,
        ///host_country,
        ///p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectAggregateExportDataWithSubdomains {
            get {
                return ResourceManager.GetString("SelectAggregateExportDataWithSubdomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///SUM({TotalEmailsSumFiltered}) as `total_emails`
        ///FROM `domain_date_provider`
        ///WHERE domain = @domain
        ///AND date BETWEEN @startDate AND @endDate
        ///AND provider = &apos;All Providers&apos;
        ///{CategoryFilter}
        ///    .
        /// </summary>
        internal static string SelectAllProviderCount {
            get {
                return ResourceManager.GetString("SelectAllProviderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///SUM({TotalEmailsSumFiltered}) as `total_emails`
        ///FROM `domain_date_provider_rollup`
        ///WHERE domain = @domain
        ///AND date BETWEEN @startDate AND @endDate
        ///AND provider = &apos;All Providers&apos;
        ///{CategoryFilter}
        ///    .
        /// </summary>
        internal static string SelectAllProviderRollupCount {
            get {
                return ResourceManager.GetString("SelectAllProviderRollupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT `domain`,
        ///`provider`,
        ///`ip`,
        ///`dkim_domain`,
        ///`dkim_selector`,
        ///SUM(`dkim_pass`) as `dkim_pass`,
        ///SUM(`dkim_fail`) as `dkim_fail`
        ///FROM `domain_date_provider_ip_dkim`
        ///WHERE domain = @domain
        ///AND provider = @provider
        ///AND ip = @ip
        ///AND date BETWEEN @startDate AND @endDate
        ///GROUP BY `dkim_domain`, `dkim_selector`;
        ///    .
        /// </summary>
        internal static string SelectDkimDomainStats {
            get {
                return ResourceManager.GetString("SelectDkimDomainStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///	SUM({FullyTrustedSum}) as TotalFullyTrusted,
        ///	SUM({PartiallyTrustedSum}) as TotalPartiallyTrusted,
        ///	SUM({UntrustedSum}) as TotalUntrusted,
        ///	SUM({QuarantinedSum}) as TotalQuarantined,
        ///	SUM({RejectedSum}) as TotalRejected,
        ///	SUM({TotalEmailsSumFiltered}) as TotalEmails
        ///FROM `domain_date_rollup` as a
        ///WHERE domain = @domain
        ///AND date BETWEEN @startDate AND @endDate
        ///{CategoryFilter}
        ///    .
        /// </summary>
        internal static string SelectDomainRollupStatsSummary {
            get {
                return ResourceManager.GetString("SelectDomainRollupStatsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT `domain`,
        ///`date`,
        ///`spf_pass_dkim_pass_none`,
        ///`spf_pass_dkim_fail_none`,
        ///`spf_fail_dkim_pass_none`,
        ///`spf_fail_dkim_fail_none`,
        ///`spf_pass_dkim_pass_quarantine`,
        ///`spf_pass_dkim_fail_quarantine`,
        ///`spf_fail_dkim_pass_quarantine`,
        ///`spf_fail_dkim_fail_quarantine`,
        ///`spf_pass_dkim_pass_reject`,
        ///`spf_pass_dkim_fail_reject`,
        ///`spf_fail_dkim_pass_reject`,
        ///`spf_fail_dkim_fail_reject`
        ///FROM `domain_date`
        ///WHERE domain = @domain
        ///AND date BETWEEN @startDate AND @endDate
        ///{CategoryFilter}
        ///    .
        /// </summary>
        internal static string SelectDomainStats {
            get {
                return ResourceManager.GetString("SelectDomainStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///	SUM({FullyTrustedSum}) as TotalFullyTrusted,
        ///	SUM({PartiallyTrustedSum}) as TotalPartiallyTrusted,
        ///	SUM({UntrustedSum}) as TotalUntrusted,
        ///	SUM({QuarantinedSum}) as TotalQuarantined,
        ///	SUM({RejectedSum}) as TotalRejected,
        ///	SUM({TotalEmailsSumFiltered}) as TotalEmails
        ///FROM `domain_date` as a
        ///WHERE domain = @domain
        ///AND date BETWEEN @startDate AND @endDate
        ///{CategoryFilter}
        ///    .
        /// </summary>
        internal static string SelectDomainStatsSummary {
            get {
                return ResourceManager.GetString("SelectDomainStatsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT `domain`,
        ///`date`,
        ///`spf_pass_dkim_pass_none`,
        ///`spf_pass_dkim_fail_none`,
        ///`spf_fail_dkim_pass_none`,
        ///`spf_fail_dkim_fail_none`,
        ///`spf_pass_dkim_pass_quarantine`,
        ///`spf_pass_dkim_fail_quarantine`,
        ///`spf_fail_dkim_pass_quarantine`,
        ///`spf_fail_dkim_fail_quarantine`,
        ///`spf_pass_dkim_pass_reject`,
        ///`spf_pass_dkim_fail_reject`,
        ///`spf_fail_dkim_pass_reject`,
        ///`spf_fail_dkim_fail_reject`
        ///FROM `domain_date_rollup`
        ///WHERE domain = @domain
        ///AND date BETWEEN @startDate AND @endDate
        ///{CategoryFilter}
        ///    .
        /// </summary>
        internal static string SelectDominStatsRollup {
            get {
                return ResourceManager.GetString("SelectDominStatsRollup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT a.*,
        ///(SELECT `hostname` FROM `domain_date_provider_ip`
        ///WHERE domain = @domain
        ///AND provider = @provider
        ///AND ip = a.ip
        ///AND date BETWEEN @startDate AND @endDate
        ///GROUP BY hostname ORDER BY count(*) DESC LIMIT 1) hostname 
        ///FROM (
        ///SELECT
        ///`domain`,
        ///`provider`,
        ///`ip`,
        ///SUM(`spf_pass_dkim_pass_none`) as `spf_pass_dkim_pass_none`,
        ///SUM(`spf_pass_dkim_fail_none`) as `spf_pass_dkim_fail_none`,
        ///SUM(`spf_fail_dkim_pass_none`) as `spf_fail_dkim_pass_none`,
        ///SUM(`spf_fail_dkim_fail_none`) as `spf_fail_d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectIpStats {
            get {
                return ResourceManager.GetString("SelectIpStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///  COUNT(ip) as `hostname_count`,
        ///  SUM(total_emails) as `total_emails`
        ///FROM (
        ///	SELECT 
        ///    ip,
        ///    SUM({TotalEmailsSum}) as `total_emails`
        ///	FROM `domain_date_provider_ip` as a
        ///	WHERE domain = @domain
        ///	AND provider = @provider
        ///	{CategoryFilter}
        ///	{IpFilter}
        ///	AND date BETWEEN @startDate AND @endDate 
        ///  GROUP BY ip
        ///) as innerQuery
        ///    .
        /// </summary>
        internal static string SelectIpStatsCount {
            get {
                return ResourceManager.GetString("SelectIpStatsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///	SUM({FullyTrustedSum}) as TotalFullyTrusted,
        ///	SUM({PartiallyTrustedSum}) as TotalPartiallyTrusted,
        ///	SUM({UntrustedSum}) as TotalUntrusted,
        ///	SUM({QuarantinedSum}) as TotalQuarantined,
        ///	SUM({RejectedSum}) as TotalRejected,
        ///	SUM({TotalEmailsSum}) as TotalEmails
        ///FROM `domain_date_provider_ip` as a
        ///WHERE domain = @domain
        ///AND provider = @provider
        ///AND date BETWEEN @startDate AND @endDate
        ///AND (@hostFilter is NULL OR hostname like @hostFilter)
        ///{CategoryFilter}
        ///    .
        /// </summary>
        internal static string SelectIpStatsSummary {
            get {
                return ResourceManager.GetString("SelectIpStatsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///	SUM({FullyTrustedSum}) as TotalFullyTrusted,
        ///	SUM({PartiallyTrustedSum}) as TotalPartiallyTrusted,
        ///	SUM({UntrustedSum}) as TotalUntrusted,
        ///	SUM({QuarantinedSum}) as TotalQuarantined,
        ///	SUM({RejectedSum}) as TotalRejected,
        ///	SUM({TotalEmailsSumFiltered}) as TotalEmails
        ///FROM `domain_date_provider_rollup` as a
        ///WHERE domain = @domain
        ///AND date BETWEEN @startDate AND @endDate
        ///{CategoryFilter}
        ///{ProviderFilter}
        ///    .
        /// </summary>
        internal static string SelectProviderRollupStatsSummary {
            get {
                return ResourceManager.GetString("SelectProviderRollupStatsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT `domain`,
        ///`provider`,
        ///SUM(`spf_pass_dkim_pass_none`) as `spf_pass_dkim_pass_none`,
        ///SUM(`spf_pass_dkim_fail_none`) as `spf_pass_dkim_fail_none`,
        ///SUM(`spf_fail_dkim_pass_none`) as `spf_fail_dkim_pass_none`,
        ///SUM(`spf_fail_dkim_fail_none`) as `spf_fail_dkim_fail_none`,
        ///SUM(`spf_pass_dkim_pass_quarantine`) as `spf_pass_dkim_pass_quarantine`,
        ///SUM(`spf_pass_dkim_fail_quarantine`) as `spf_pass_dkim_fail_quarantine`,
        ///SUM(`spf_fail_dkim_pass_quarantine`) as `spf_fail_dkim_pass_quarantine`,
        ///SUM(`spf_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectProviderStats {
            get {
                return ResourceManager.GetString("SelectProviderStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT COUNT(*) 
        ///FROM (
        ///SELECT provider
        ///FROM `domain_date_provider`
        ///WHERE domain = @domain
        ///AND date BETWEEN @startDate AND @endDate
        ///{CategoryFilter}
        ///GROUP BY provider) as tb
        ///    .
        /// </summary>
        internal static string SelectProviderStatsCount {
            get {
                return ResourceManager.GetString("SelectProviderStatsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT `domain`,
        ///`provider`,
        ///SUM(`spf_pass_dkim_pass_none`) as `spf_pass_dkim_pass_none`,
        ///SUM(`spf_pass_dkim_fail_none`) as `spf_pass_dkim_fail_none`,
        ///SUM(`spf_fail_dkim_pass_none`) as `spf_fail_dkim_pass_none`,
        ///SUM(`spf_fail_dkim_fail_none`) as `spf_fail_dkim_fail_none`,
        ///SUM(`spf_pass_dkim_pass_quarantine`) as `spf_pass_dkim_pass_quarantine`,
        ///SUM(`spf_pass_dkim_fail_quarantine`) as `spf_pass_dkim_fail_quarantine`,
        ///SUM(`spf_fail_dkim_pass_quarantine`) as `spf_fail_dkim_pass_quarantine`,
        ///SUM(`spf_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectProviderStatsRollup {
            get {
                return ResourceManager.GetString("SelectProviderStatsRollup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT COUNT(*) 
        ///FROM (
        ///SELECT provider
        ///FROM `domain_date_provider_rollup`
        ///WHERE domain = @domain
        ///AND date BETWEEN @startDate AND @endDate
        ///{CategoryFilter}
        ///GROUP BY provider) as tb
        ///    .
        /// </summary>
        internal static string SelectProviderStatsRollupCount {
            get {
                return ResourceManager.GetString("SelectProviderStatsRollupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT 
        ///	SUM({FullyTrustedSum}) as TotalFullyTrusted,
        ///	SUM({PartiallyTrustedSum}) as TotalPartiallyTrusted,
        ///	SUM({UntrustedSum}) as TotalUntrusted,
        ///	SUM({QuarantinedSum}) as TotalQuarantined,
        ///	SUM({RejectedSum}) as TotalRejected,
        ///	SUM({TotalEmailsSumFiltered}) as TotalEmails
        ///FROM `domain_date_provider` as a
        ///WHERE domain = @domain
        ///AND date BETWEEN @startDate AND @endDate
        ///{CategoryFilter}
        ///{ProviderFilter}
        ///    .
        /// </summary>
        internal static string SelectProviderStatsSummary {
            get {
                return ResourceManager.GetString("SelectProviderStatsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT `domain`,
        ///`provider`,
        ///`domain` as `subdomain`,
        ///SUM(`spf_pass_dkim_pass_none`) as `spf_pass_dkim_pass_none`,
        ///SUM(`spf_pass_dkim_fail_none`) as `spf_pass_dkim_fail_none`,
        ///SUM(`spf_fail_dkim_pass_none`) as `spf_fail_dkim_pass_none`,
        ///SUM(`spf_fail_dkim_fail_none`) as `spf_fail_dkim_fail_none`,
        ///SUM(`spf_pass_dkim_pass_quarantine`) as `spf_pass_dkim_pass_quarantine`,
        ///SUM(`spf_pass_dkim_fail_quarantine`) as `spf_pass_dkim_fail_quarantine`,
        ///SUM(`spf_fail_dkim_pass_quarantine`) as `spf_fail_dkim_pass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectSingleProviderStats {
            get {
                return ResourceManager.GetString("SelectSingleProviderStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT `domain`,
        ///`provider`,
        ///`ip`,
        ///`spf_domain`,
        ///SUM(`spf_pass`) as `spf_pass`,
        ///SUM(`spf_fail`) as `spf_fail`
        ///FROM `domain_date_provider_ip_spf`
        ///WHERE domain = @domain
        ///AND provider = @provider
        ///AND ip = @ip
        ///AND date BETWEEN @startDate AND @endDate
        ///GROUP BY `spf_domain`;
        ///    .
        /// </summary>
        internal static string SelectSpfDomainStats {
            get {
                return ResourceManager.GetString("SelectSpfDomainStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT COUNT(*) 
        ///FROM (
        ///SELECT subdomain
        ///FROM `domain_date_provider_subdomain`
        ///WHERE domain = @domain
        ///AND provider = @provider
        ///AND date BETWEEN @startDate AND @endDate
        ///{CategoryFilter}
        ///GROUP BY subdomain) as tb
        ///    .
        /// </summary>
        internal static string SelectSubdomainCount {
            get {
                return ResourceManager.GetString("SelectSubdomainCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT `domain`,
        ///`provider`,
        ///`subdomain`,
        ///SUM(`spf_pass_dkim_pass_none`) as `spf_pass_dkim_pass_none`,
        ///SUM(`spf_pass_dkim_fail_none`) as `spf_pass_dkim_fail_none`,
        ///SUM(`spf_fail_dkim_pass_none`) as `spf_fail_dkim_pass_none`,
        ///SUM(`spf_fail_dkim_fail_none`) as `spf_fail_dkim_fail_none`,
        ///SUM(`spf_pass_dkim_pass_quarantine`) as `spf_pass_dkim_pass_quarantine`,
        ///SUM(`spf_pass_dkim_fail_quarantine`) as `spf_pass_dkim_fail_quarantine`,
        ///SUM(`spf_fail_dkim_pass_quarantine`) as `spf_fail_dkim_pass_quarantin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectSubdomainStats {
            get {
                return ResourceManager.GetString("SelectSubdomainStats", resourceCulture);
            }
        }
    }
}
