//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.AggregateReport.Api.V2.Dao {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AggregateReportDaoV2 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AggregateReportDaoV2() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MailCheck.AggregateReport.Api.V2.Dao.AggregateReportDaoV2", typeof(AggregateReportDaoV2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SelectAllProviderCount {
            get {
                return ResourceManager.GetString("SelectAllProviderCount", resourceCulture);
            }
        }
        
        internal static string SelectAllProviderRollupCount {
            get {
                return ResourceManager.GetString("SelectAllProviderRollupCount", resourceCulture);
            }
        }
        
        internal static string SelectDomainStats {
            get {
                return ResourceManager.GetString("SelectDomainStats", resourceCulture);
            }
        }
        
        internal static string SelectDominStatsRollup {
            get {
                return ResourceManager.GetString("SelectDominStatsRollup", resourceCulture);
            }
        }
        
        internal static string SelectProviderStats {
            get {
                return ResourceManager.GetString("SelectProviderStats", resourceCulture);
            }
        }
        
        internal static string SelectProviderStatsCount {
            get {
                return ResourceManager.GetString("SelectProviderStatsCount", resourceCulture);
            }
        }
        
        internal static string SelectProviderStatsRollup {
            get {
                return ResourceManager.GetString("SelectProviderStatsRollup", resourceCulture);
            }
        }
        
        internal static string SelectProviderStatsRollupCount {
            get {
                return ResourceManager.GetString("SelectProviderStatsRollupCount", resourceCulture);
            }
        }
        
        internal static string SelectSingleProviderStats {
            get {
                return ResourceManager.GetString("SelectSingleProviderStats", resourceCulture);
            }
        }
        
        internal static string SelectSubdomainCount {
            get {
                return ResourceManager.GetString("SelectSubdomainCount", resourceCulture);
            }
        }
        
        internal static string SelectSubdomainStats {
            get {
                return ResourceManager.GetString("SelectSubdomainStats", resourceCulture);
            }
        }
        
        internal static string SelectIpStats {
            get {
                return ResourceManager.GetString("SelectIpStats", resourceCulture);
            }
        }
        
        internal static string SelectSpfDomainStats {
            get {
                return ResourceManager.GetString("SelectSpfDomainStats", resourceCulture);
            }
        }
        
        internal static string SelectIpStatsCount {
            get {
                return ResourceManager.GetString("SelectIpStatsCount", resourceCulture);
            }
        }
        
        internal static string SelectDkimDomainStats {
            get {
                return ResourceManager.GetString("SelectDkimDomainStats", resourceCulture);
            }
        }
        
        internal static string FilterByFullyTrusted {
            get {
                return ResourceManager.GetString("FilterByFullyTrusted", resourceCulture);
            }
        }
        
        internal static string FilterByPartiallyTrusted {
            get {
                return ResourceManager.GetString("FilterByPartiallyTrusted", resourceCulture);
            }
        }
        
        internal static string FilterByQuarantined {
            get {
                return ResourceManager.GetString("FilterByQuarantined", resourceCulture);
            }
        }
        
        internal static string FilterByRejected {
            get {
                return ResourceManager.GetString("FilterByRejected", resourceCulture);
            }
        }
        
        internal static string FilterByUntrused {
            get {
                return ResourceManager.GetString("FilterByUntrused", resourceCulture);
            }
        }
        
        internal static string FilterByProvider {
            get {
                return ResourceManager.GetString("FilterByProvider", resourceCulture);
            }
        }
        
        internal static string SelectIpStatsSummary {
            get {
                return ResourceManager.GetString("SelectIpStatsSummary", resourceCulture);
            }
        }
        
        internal static string SelectDomainRollupStatsSummary {
            get {
                return ResourceManager.GetString("SelectDomainRollupStatsSummary", resourceCulture);
            }
        }
        
        internal static string SelectDomainStatsSummary {
            get {
                return ResourceManager.GetString("SelectDomainStatsSummary", resourceCulture);
            }
        }
        
        internal static string SelectProviderRollupStatsSummary {
            get {
                return ResourceManager.GetString("SelectProviderRollupStatsSummary", resourceCulture);
            }
        }
        
        internal static string SelectProviderStatsSummary {
            get {
                return ResourceManager.GetString("SelectProviderStatsSummary", resourceCulture);
            }
        }
        
        internal static string SelectAggregateExportData {
            get {
                return ResourceManager.GetString("SelectAggregateExportData", resourceCulture);
            }
        }
        
        internal static string SelectAggregateExportDataWithSubdomains {
            get {
                return ResourceManager.GetString("SelectAggregateExportDataWithSubdomains", resourceCulture);
            }
        }
        
        internal static string FilterByIp {
            get {
                return ResourceManager.GetString("FilterByIp", resourceCulture);
            }
        }
    }
}
