//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Intelligence.IpToAsnParser.Dao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ip6ToAsnDaoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ip6ToAsnDaoResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Intelligence.IpToAsnParser.Dao.Ip6ToAsnDaoResource", typeof(Ip6ToAsnDaoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO public.ip6_address_to_asn (ip_address,asn) VALUES.
        /// </summary>
        public static string InsertIpToAsn {
            get {
                return ResourceManager.GetString("InsertIpToAsn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON CONFLICT (ip_address, asn) DO NOTHING;.
        /// </summary>
        public static string InsertIpToAsnOnConflict {
            get {
                return ResourceManager.GetString("InsertIpToAsnOnConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (CAST(@ip_address_{0} AS cidr), @asn_{0}).
        /// </summary>
        public static string InsertTpToAsnValueFormatString {
            get {
                return ResourceManager.GetString("InsertTpToAsnValueFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REFRESH MATERIALIZED VIEW CONCURRENTLY ip6_address_to_asn_mv;.
        /// </summary>
        public static string RefreshMaterializedView {
            get {
                return ResourceManager.GetString("RefreshMaterializedView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM public.ip6_address_to_asn;.
        /// </summary>
        public static string Truncate {
            get {
                return ResourceManager.GetString("Truncate", resourceCulture);
            }
        }
    }
}
