//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.Intelligence.Enricher.Dao {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AsDaoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AsDaoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.Intelligence.Enricher.Dao.AsDaoResources", typeof(AsDaoResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT host({0}) as ip_address, {1} as original_ip_address, asn.asn, asn.description, country
        ///FROM ip_address_to_asn_mv ip
        ///JOIN asn_to_description_and_country_mv asn on ip.asn = asn.asn
        ///WHERE ip.ip_address &gt;&gt;= {0}
        ///ORDER by masklen(ip.ip_address) DESC
        ///LIMIT 1.
        /// </summary>
        public static string SelectIp4AsNumber {
            get {
                return ResourceManager.GetString("SelectIp4AsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT host({0}) as ip_address, {1} as original_ip_address, asn.asn, asn.description, country
        ///FROM ip6_address_to_asn_mv ip
        ///JOIN asn_to_description_and_country_mv asn on ip.asn = asn.asn
        ///WHERE ip.ip_address &gt;&gt;= {0}
        ///ORDER by masklen(ip.ip_address) DESC
        ///LIMIT 1.
        /// </summary>
        public static string SelectIp6AsNumber {
            get {
                return ResourceManager.GetString("SelectIp6AsNumber", resourceCulture);
            }
        }
    }
}
