//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailCheck.AggregateReport.Parser.Test.Serialisation.AggregateReportDeserialisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpfAuthResultsDeserialiserTestsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpfAuthResultsDeserialiserTestsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MailCheck.AggregateReport.Parser.Test.Serialisation.AggregateReportDeserialisatio" +
                            "n.SpfAuthResultsDeserialiserTestsResource", typeof(SpfAuthResultsDeserialiserTestsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;spf&amp;gt;
        ///	&amp;lt;domain&amp;gt;gov.uk&amp;lt;/domain&amp;gt;
        ///	&amp;lt;domain&amp;gt;gov.uk&amp;lt;/domain&amp;gt;
        ///	&amp;lt;result&amp;gt;temperror&amp;lt;/result&amp;gt;
        /// &amp;lt;/spf&amp;gt;.
        /// </summary>
        public static string DuplicateDomain {
            get {
                return ResourceManager.GetString("DuplicateDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;spf&amp;gt;
        ///	&amp;lt;domain&amp;gt;gov.uk&amp;lt;/domain&amp;gt;
        ///	&amp;lt;result&amp;gt;temperror&amp;lt;/result&amp;gt;
        ///	&amp;lt;result&amp;gt;temperror&amp;lt;/result&amp;gt;
        /// &amp;lt;/spf&amp;gt;.
        /// </summary>
        public static string DuplicateResult {
            get {
                return ResourceManager.GetString("DuplicateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;spf&amp;gt;
        ///	&amp;lt;domain&amp;gt;gov.uk&amp;lt;/domain&amp;gt;
        ///	&amp;lt;result&amp;gt;asdf&amp;lt;/result&amp;gt;
        /// &amp;lt;/spf&amp;gt;.
        /// </summary>
        public static string InvalidResult {
            get {
                return ResourceManager.GetString("InvalidResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    &lt;spf&gt;
        ///      &lt;result&gt;neutral&lt;/result&gt;
        ///    &lt;/spf&gt;
        ///.
        /// </summary>
        public static string NoDomainTag {
            get {
                return ResourceManager.GetString("NoDomainTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    &lt;spf&gt;
        ///      &lt;result&gt;none&lt;/result&gt;
        ///    &lt;/spf&gt;
        ///.
        /// </summary>
        public static string NoDomainTagResultNone {
            get {
                return ResourceManager.GetString("NoDomainTagResultNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;spf&amp;gt;
        ///	&amp;lt;domain&amp;gt;gov.uk&amp;lt;/domain&amp;gt;
        /// &amp;lt;/spf&amp;gt;.
        /// </summary>
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;spf&amp;gt;
        ///	 &amp;lt;not_spf&amp;gt;
        ///		&amp;lt;domain&amp;gt;gov.uk&amp;lt;/domain&amp;gt;
        ///		&amp;lt;result&amp;gt;temperror&amp;lt;/result&amp;gt;
        ///	 &amp;lt;/not_spf&amp;gt;
        /// &amp;lt;/spf&amp;gt;.
        /// </summary>
        public static string NotDirectDescendants {
            get {
                return ResourceManager.GetString("NotDirectDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;not_spf&amp;gt;
        ///	&amp;lt;domain&amp;gt;gov.uk&amp;lt;/domain&amp;gt;
        ///	&amp;lt;result&amp;gt;temperror&amp;lt;/result&amp;gt;
        /// &amp;lt;/not_spf&amp;gt;.
        /// </summary>
        public static string NotSpf {
            get {
                return ResourceManager.GetString("NotSpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;spf&amp;gt;
        ///	&amp;lt;domain&amp;gt;gov.uk&amp;lt;/domain&amp;gt;
        ///	&amp;lt;result&amp;gt;temperror&amp;lt;/result&amp;gt;
        /// &amp;lt;/spf&amp;gt;.
        /// </summary>
        public static string SpfAuthResultStandard {
            get {
                return ResourceManager.GetString("SpfAuthResultStandard", resourceCulture);
            }
        }
    }
}
